language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test
scala:
  - 2.11.7
  - 2.10.5
jdk:
  - oraclejdk7
  - openjdk7
sudo: required # for setting hostname
addons:
  hostname: localhost #https://github.com/travis-ci/travis-ci/issues/5227
notifications:
  email:
    - guntiso@uniso.lv
